name: semverify

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Install semverify
      run: |
        dotnet --info
        dotnet tool install -g semverify-dotnet-tool --version 0.1.7-alpha01
    - name: dotnet publish
      run: dotnet publish -f netstandard2.0 -c Release -o Assemblies ./src/Marten/Marten.csproj
    - name: Run semverify for the current commit
      run: $HOME/.dotnet/tools/semverify Marten@3.9.0 Assemblies/Marten.dll --expected-change-type Minor --use-dependency-changes
      env:
        DOTNET_ROOT: /opt/hostedtoolcache/dncs/3.0.100/x64
